import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import { Navbar } from "@/components/Navbar";
import Store from "@/store/store";
import { SupenseWrapper } from "@/components/SuspenseComp";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Genshin/Hsr-Showcase",
  description: "Generated by create next app",
};

const genshinFont = localFont({
  src: [
    {
      path: "../../public/fonts/Default_JP.ttf",
      weight: "200"
    }
  ],
  variable: "--font-genshin"
})

Store
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${genshinFont.variable}`}>
      <body className={inter.className}>
        <Store>
          <SupenseWrapper>

          <div className=" flex flex-col items-center gap-[5vh] container mx-auto px-4 mt-[2vh]">
            <Navbar />
            <div className="pb-8">
              {children}
            </div>
          </div>
          </SupenseWrapper>
        </Store>
      </body>
    </html>
  );
}
